### ISSUE TITLE
Works perfectly well with other engines too

### ISSUE THREAD

**Issue by michapixel** [debute/laravel-mix-blade-reload#2]
`mix
	.bladeReload({
		path: 'resources/views/**/*.antlers.html',
		debug:false
	});
;`

**Comment by krehak** [comment]
It's a simple extension watching for a "change" event on the files, so it doesn't surprise me. Thanks for trying out another engine!

**Comment by michapixel** [comment]
Just wanted to say thank you but in overexcitement almost forgot.
So thank you and you might consider giving it a more generic name ;)

**Comment by krehak** [comment]
Thanks, I will think about a better name :)
